[phases.setup]
nixPkgs = ["nodejs_20"]
cmds = ["corepack enable", "corepack prepare pnpm@latest --activate"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter back build"]

[start]
cmd = "pnpm --filter back start"
